# Generated by Django 5.1.2 on 2024-11-01 15:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='введите email', max_length=100, verbose_name='email')),
                ('name_surname', models.CharField(help_text='введите Ф.И.О.', max_length=200, verbose_name='Ф.И.О')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_theme', models.CharField(help_text='напишите тему письма', max_length=200, verbose_name='тема письма')),
                ('letter_body', models.TextField(blank=True, help_text='вводите текст письма здесь', null=True, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата и время первой отправки рассылки')),
                ('periodicity', models.CharField(max_length=150, verbose_name='периодичность: раз в день, раз в неделю, раз в месяц')),
                ('status', models.CharField(max_length=150, verbose_name='статус рассылки')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='newsletter.message', verbose_name='сообщение')),
                ('client', models.ManyToManyField(to='newsletter.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата и время последней попытки')),
                ('status', models.CharField(max_length=150, verbose_name='статус попытки')),
                ('server_responce', models.CharField(max_length=150, verbose_name='ответ постового сервера')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter', verbose_name='попытка рассылки')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
    ]
