# Generated by Django 5.1.2 on 2024-11-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(help_text='необходимо выбрать хотя бы одного клиента', to='newsletter.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.OneToOneField(help_text='обязательное поле', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='newsletter.message', verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('MINUTLY', 'раз в минуту'), ('DAILY', 'раз в день'), ('WEEKLY', 'раз в неделю'), ('MONTHLY', 'раз в месяц')], default=('daily',), max_length=150, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('FINISHED', 'Завершена')], default='Создана', max_length=150, verbose_name='статус рассылки'),
        ),
    ]
