# Generated by Django 5.1.2 on 2024-11-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_client_alter_newsletter_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Неуспешно', 'Неуспешно')], max_length=150, verbose_name='статус попытки'),
        ),
    ]
