# Generated by Django 5.1.2 on 2024-11-08 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_mailingattempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='date_time',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата начала'),
        ),
    ]
