# Generated by Django 5.1.2 on 2024-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_rename_server_responce_mailingattempt_server_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки'),
        ),
    ]
