# Generated by Django 4.2.2 on 2024-11-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('can_change_status', 'can change newsletter status'), ('can_view_newsletters', 'can view newsletters')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
